apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-nodejs-docker
  labels:
    app: api-nodejs-docker
spec:
  replicas: 20
  selector:
    matchLabels:
      app: api-nodejs-docker
  template:
    metadata:
      labels:
        app: api-nodejs-docker
    spec:
      containers:
      - name: api-nodejs-docker
        image: acrtccdj.azurecr.io/api-nodejs-docker:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: api-nodejs-docker
spec:
  selector:
    app: api-nodejs-docker
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer